name: qa4sm_reader
channels:
- defaults
- conda-forge
dependencies:
- xarray
- netcdf4
- pandas
- numpy>=2.0.0
- matplotlib
- cartopy==0.22.0
- pyproj
- h5netcdf
- pip
- pip:
    - parse
    - colorcet
    - scipy
    - seaborn
    - pygeogrids
    - pytest
    - pytest-cov
    - pytesmo
    - cftime
